//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 04:00:54 PM PST 
//


package com.microsoft.schemas.hpcs2008r2.common;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.microsoft.schemas.hpcs2008r2.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.schemas.hpcs2008r2.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfProperty }
     * 
     */
    public ArrayOfProperty createArrayOfProperty() {
        return new ArrayOfProperty();
    }

    /**
     * Create an instance of {@link ArrayOfObject }
     * 
     */
    public ArrayOfObject createArrayOfObject() {
        return new ArrayOfObject();
    }

    /**
     * Create an instance of {@link ArrayOfObject.Object }
     * 
     */
    public ArrayOfObject.Object createArrayOfObjectObject() {
        return new ArrayOfObject.Object();
    }

    /**
     * Create an instance of {@link ArrayOfObject.Object.Properties }
     * 
     */
    public ArrayOfObject.Object.Properties createArrayOfObjectObjectProperties() {
        return new ArrayOfObject.Object.Properties();
    }

    /**
     * Create an instance of {@link ArrayOfProperty.Property }
     * 
     */
    public ArrayOfProperty.Property createArrayOfPropertyProperty() {
        return new ArrayOfProperty.Property();
    }

    /**
     * Create an instance of {@link ArrayOfObject.Object.Properties.Property }
     * 
     */
    public ArrayOfObject.Object.Properties.Property createArrayOfObjectObjectPropertiesProperty() {
        return new ArrayOfObject.Object.Properties.Property();
    }

}
