//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 04:00:54 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.microsoft.com/HPCS2008R2/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.microsoft.schemas.hpcs2008r2.common;
