//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestSender.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IPrimeFactorization")]
    public interface IPrimeFactorization {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimeFactorization/Factorize", ReplyAction="http://tempuri.org/IPrimeFactorization/FactorizeResponse")]
        RequestSender.ServiceReference.FactorizeResponse Factorize(RequestSender.ServiceReference.FactorizeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Factorize", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FactorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int n;
        
        public FactorizeRequest() {
        }
        
        public FactorizeRequest(int n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FactorizeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FactorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] FactorizeResult;
        
        public FactorizeResponse() {
        }
        
        public FactorizeResponse(int[] FactorizeResult) {
            this.FactorizeResult = FactorizeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrimeFactorizationChannel : RequestSender.ServiceReference.IPrimeFactorization, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimeFactorizationClient : System.ServiceModel.ClientBase<RequestSender.ServiceReference.IPrimeFactorization>, RequestSender.ServiceReference.IPrimeFactorization {
        
        public PrimeFactorizationClient() {
        }
        
        public PrimeFactorizationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimeFactorizationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimeFactorizationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimeFactorizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RequestSender.ServiceReference.FactorizeResponse Factorize(RequestSender.ServiceReference.FactorizeRequest request) {
            return base.Channel.Factorize(request);
        }
    }
}
