//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStaticWorkbookService")]
public interface IStaticWorkbookService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticWorkbookService/CalculateParameters", ReplyAction="http://tempuri.org/IStaticWorkbookService/CalculateParametersResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    CalculateParametersResponse CalculateParameters(CalculateParametersRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStaticWorkbookService/CalculateParameters", ReplyAction="http://tempuri.org/IStaticWorkbookService/CalculateParametersResponse")]
    System.IAsyncResult BeginCalculateParameters(CalculateParametersRequest request, System.AsyncCallback callback, object asyncState);
    
    CalculateParametersResponse EndCalculateParameters(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CalculateParameters", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class CalculateParametersRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string spreadsheetPath;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string[] inputRanges;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public object[] inputValues;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
    public string[] outputRanges;
    
    public CalculateParametersRequest()
    {
    }
    
    public CalculateParametersRequest(string spreadsheetPath, string[] inputRanges, object[] inputValues, string[] outputRanges)
    {
        this.spreadsheetPath = spreadsheetPath;
        this.inputRanges = inputRanges;
        this.inputValues = inputValues;
        this.outputRanges = outputRanges;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CalculateParametersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class CalculateParametersResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public object[] CalculateParametersResult;
    
    public CalculateParametersResponse()
    {
    }
    
    public CalculateParametersResponse(object[] CalculateParametersResult)
    {
        this.CalculateParametersResult = CalculateParametersResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStaticWorkbookServiceChannel : IStaticWorkbookService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StaticWorkbookServiceClient : System.ServiceModel.ClientBase<IStaticWorkbookService>, IStaticWorkbookService
{
    
    public StaticWorkbookServiceClient()
    {
    }
    
    public StaticWorkbookServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StaticWorkbookServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StaticWorkbookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StaticWorkbookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CalculateParametersResponse CalculateParameters(CalculateParametersRequest request)
    {
        return base.Channel.CalculateParameters(request);
    }
    
    public System.IAsyncResult BeginCalculateParameters(CalculateParametersRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCalculateParameters(request, callback, asyncState);
    }
    
    public CalculateParametersResponse EndCalculateParameters(System.IAsyncResult result)
    {
        return base.Channel.EndCalculateParameters(result);
    }
}
