//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Hpc.EchoSvcClient.Durable
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StatisticInfo", Namespace = "http://schemas.datacontract.org/2004/07/EchoSvcLib")]
    [System.SerializableAttribute()]
    public partial class StatisticInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endTimeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startTimeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int taskIdField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                if ((this.endTimeField.Equals(value) != true))
                {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                if ((this.startTimeField.Equals(value) != true))
                {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                if ((this.taskIdField.Equals(value) != true))
                {
                    this.taskIdField = value;
                    this.RaisePropertyChanged("taskId");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Microsoft.Hpc.EchoSvcClient.IEchoSvc")]
    public interface IEchoSvc
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/Echo", ReplyAction = "http://tempuri.org/IEchoSvc/EchoResponse")]
        Microsoft.Hpc.EchoSvcClient.Durable.EchoResponse Echo(Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/Echo", ReplyAction = "http://tempuri.org/IEchoSvc/EchoResponse")]
        System.IAsyncResult BeginEcho(Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest request, System.AsyncCallback callback, object asyncState);

        Microsoft.Hpc.EchoSvcClient.Durable.EchoResponse EndEcho(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/GenerateLoad", ReplyAction = "http://tempuri.org/IEchoSvc/GenerateLoadResponse")]
        Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadResponse GenerateLoad(Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/GenerateLoad", ReplyAction = "http://tempuri.org/IEchoSvc/GenerateLoadResponse")]
        System.IAsyncResult BeginGenerateLoad(Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest request, System.AsyncCallback callback, object asyncState);

        Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadResponse EndGenerateLoad(System.IAsyncResult result);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "Echo", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class EchoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string input;

        public EchoRequest()
        {
        }

        public EchoRequest(string input)
        {
            this.input = input;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EchoResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class EchoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string EchoResult;

        public EchoResponse()
        {
        }

        public EchoResponse(string EchoResult)
        {
            this.EchoResult = EchoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GenerateLoad", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GenerateLoadRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public double runMilliSeconds;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public byte[] dummyData;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        public string fileData;

        public GenerateLoadRequest()
        {
        }

        public GenerateLoadRequest(double runMilliSeconds, byte[] dummyData, string fileData)
        {
            this.runMilliSeconds = runMilliSeconds;
            this.dummyData = dummyData;
            this.fileData = fileData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GenerateLoadResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GenerateLoadResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public Microsoft.Hpc.EchoSvcClient.Durable.StatisticInfo GenerateLoadResult;

        public GenerateLoadResponse()
        {
        }

        public GenerateLoadResponse(Microsoft.Hpc.EchoSvcClient.Durable.StatisticInfo GenerateLoadResult)
        {
            this.GenerateLoadResult = GenerateLoadResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IEchoSvcChannel : Microsoft.Hpc.EchoSvcClient.Durable.IEchoSvc, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EchoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public EchoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public Microsoft.Hpc.EchoSvcClient.Durable.EchoResponse Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((Microsoft.Hpc.EchoSvcClient.Durable.EchoResponse)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GenerateLoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GenerateLoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadResponse Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadResponse)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EchoSvcClient : System.ServiceModel.ClientBase<Microsoft.Hpc.EchoSvcClient.Durable.IEchoSvc>, Microsoft.Hpc.EchoSvcClient.Durable.IEchoSvc
    {

        private BeginOperationDelegate onBeginEchoDelegate;

        private EndOperationDelegate onEndEchoDelegate;

        private System.Threading.SendOrPostCallback onEchoCompletedDelegate;

        private BeginOperationDelegate onBeginGenerateLoadDelegate;

        private EndOperationDelegate onEndGenerateLoadDelegate;

        private System.Threading.SendOrPostCallback onGenerateLoadCompletedDelegate;

        public EchoSvcClient()
        {
        }

        public EchoSvcClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public EchoSvcClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EchoSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EchoSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public event System.EventHandler<EchoCompletedEventArgs> EchoCompleted;

        public event System.EventHandler<GenerateLoadCompletedEventArgs> GenerateLoadCompleted;

        public Microsoft.Hpc.EchoSvcClient.Durable.EchoResponse Echo(Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest request)
        {
            return base.Channel.Echo(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEcho(Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginEcho(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Microsoft.Hpc.EchoSvcClient.Durable.EchoResponse EndEcho(System.IAsyncResult result)
        {
            return base.Channel.EndEcho(result);
        }

        private System.IAsyncResult OnBeginEcho(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest request = ((Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest)(inValues[0]));
            return this.BeginEcho(request, callback, asyncState);
        }

        private object[] OnEndEcho(System.IAsyncResult result)
        {
            Microsoft.Hpc.EchoSvcClient.Durable.EchoResponse retVal = this.EndEcho(result);
            return new object[] {
                    retVal};
        }

        private void OnEchoCompleted(object state)
        {
            if ((this.EchoCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EchoCompleted(this, new EchoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void EchoAsync(Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest request)
        {
            this.EchoAsync(request, null);
        }

        public void EchoAsync(Microsoft.Hpc.EchoSvcClient.Durable.EchoRequest request, object userState)
        {
            if ((this.onBeginEchoDelegate == null))
            {
                this.onBeginEchoDelegate = new BeginOperationDelegate(this.OnBeginEcho);
            }
            if ((this.onEndEchoDelegate == null))
            {
                this.onEndEchoDelegate = new EndOperationDelegate(this.OnEndEcho);
            }
            if ((this.onEchoCompletedDelegate == null))
            {
                this.onEchoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEchoCompleted);
            }
            base.InvokeAsync(this.onBeginEchoDelegate, new object[] {
                        request}, this.onEndEchoDelegate, this.onEchoCompletedDelegate, userState);
        }

        public Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadResponse GenerateLoad(Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest request)
        {
            return base.Channel.GenerateLoad(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGenerateLoad(Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGenerateLoad(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadResponse EndGenerateLoad(System.IAsyncResult result)
        {
            return base.Channel.EndGenerateLoad(result);
        }

        private System.IAsyncResult OnBeginGenerateLoad(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest request = ((Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest)(inValues[0]));
            return this.BeginGenerateLoad(request, callback, asyncState);
        }

        private object[] OnEndGenerateLoad(System.IAsyncResult result)
        {
            Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadResponse retVal = this.EndGenerateLoad(result);
            return new object[] {
                    retVal};
        }

        private void OnGenerateLoadCompleted(object state)
        {
            if ((this.GenerateLoadCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GenerateLoadCompleted(this, new GenerateLoadCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GenerateLoadAsync(Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest request)
        {
            this.GenerateLoadAsync(request, null);
        }

        public void GenerateLoadAsync(Microsoft.Hpc.EchoSvcClient.Durable.GenerateLoadRequest request, object userState)
        {
            if ((this.onBeginGenerateLoadDelegate == null))
            {
                this.onBeginGenerateLoadDelegate = new BeginOperationDelegate(this.OnBeginGenerateLoad);
            }
            if ((this.onEndGenerateLoadDelegate == null))
            {
                this.onEndGenerateLoadDelegate = new EndOperationDelegate(this.OnEndGenerateLoad);
            }
            if ((this.onGenerateLoadCompletedDelegate == null))
            {
                this.onGenerateLoadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGenerateLoadCompleted);
            }
            base.InvokeAsync(this.onBeginGenerateLoadDelegate, new object[] {
                        request}, this.onEndGenerateLoadDelegate, this.onGenerateLoadCompletedDelegate, userState);
        }
    }
}
